language: python
python:
  - "2.7"
#  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
virtualenv:
  system_site_packages: true

before_install: sudo apt-get update -qq

install:
 - sudo apt-get install -qq python-libxml2 python-libxslt1 python-pypoker-eval python-cjson bc
 - pip install http://github.com/pokermania/pokerdistutils/archive/master.zip
 - pip install http://github.com/pokermania/reflogging/archive/master.zip

# command to run tests, e.g. python setup.py test
before_script: python setup.py build
script:  python setup.py test -p
