language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: apt-get install python-libxml2 python-libxslt1 python-pypoker-eval && \
	git clone git://github.com/tuco86/poker-distutils.git /tmp/poker-distutils &&
		pip install /tmp/poker-distutils &&
	git clone https://github.com/pokermania/reflogging /tmp/reflogging &&
		pip install /tmp/reflogging
# command to run tests, e.g. python setup.py test
script:  python setup.py test
