language: python
python:
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-libxml2 python-libxslt1 python-pypoker-eval
 - git clone git://github.com/tuco86/poker-distutils.git /tmp/poker-distutils && sudo pip install /tmp/poker-distutils
 - git clone https://github.com/pokermania/reflogging /tmp/reflogging && sudo pip install /tmp/reflogging

# command to run tests, e.g. python setup.py test
script:  python setup.py test
