language: python
python:
  - "2.7"
#  - "2.6"
virtualenv:
  system_site_packages: true

before_install: sudo apt-get update

install:
 - sudo apt-get install
    python-libxml2
    python-libxslt1
    python-pypoker-eval
    python-cjson bc
 - pip install
    nose
    rednose
    http://github.com/pokermania/pokerdistutils/archive/master.zip
    http://github.com/pokermania/reflogging/archive/master.zip

before_script: python setup.py build
script: nosetests --exe --rednose tests
